#!/bin/bash
# bash <(curl -s https://raw.githubusercontent.com/jeffwilson515/penguin/main/crostini-dev)

#Downloads where we put stuff
cd ~
mkdir -p ~/Downloads
cd ~/Downloads

#Basic utilities
sudo apt install iputils-ping -y
sudo apt install traceroute -y
sudo apt install dnsutils -y
sudo apt install apt-file -y
# sudo apt install fuse -y
# sudo apt install xz-utils -y
# sudo apt install gnupg2 -y

#VS Code
curl -L https://go.microsoft.com/fwlink/?LinkID=760868 > ~/Downloads/vscode.deb
sudo apt install ~/Downloads/vscode.deb -y

#PowerShell
source /etc/os-release
curl -L https://packages.microsoft.com/config/debian/$VERSION_ID/packages-microsoft-prod.deb > ~/Downloads/packages-microsoft-prod.deb
sudo dpkg -i ~/Downloads/packages-microsoft-prod.deb
rm ~/Downloads/packages-microsoft-prod.deb
sudo apt install powershell -y

# Chrome
curl -L https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb > ~/Downloads/chrome.deb
sudo apt install ~/Downloads/chrome.deb -y

#Webex Teams
mkdir -p ~/.local/share
curl -L https://binaries.webex.com/WebexDesktop-Ubuntu-Official-Package/Webex.deb > ~/Downloads/Webex.deb
sudo apt install ~/Downloads/Webex.deb -y

#Upgate everything
sudo apt-file update
sudo apt update
sudo apt upgrade -y
