#!/bin/bash
# bash <(curl -s https://raw.githubusercontent.com/jeffwilson515/penguin/main/crostini-dev)

# Downloads where we put stuff
cd ~
mkdir -p ~/Downloads
cd ~/Downloads

# Basic utilities
sudo apt install iputils-ping -y
sudo apt install traceroute -y
sudo apt install dnsutils -y
sudo apt install apt-file -y
# following needed for sql server
sudo apt install gnupg2 -y
sudo apt install apt-transport-https -y

# Gnome Keyring
sudo apt install gnome-keyring -y

# VS Code
curl -L https://go.microsoft.com/fwlink/?LinkID=760868 > ~/Downloads/vscode.deb
sudo apt install ~/Downloads/vscode.deb -y
mkdir -p ~/.vscode
curl -L https://raw.githubusercontent.com/jeffwilson515/penguin/main/argv.json > ~/.vscode/argv.json

# Azure Data Studio
curl -L https://go.microsoft.com/fwlink/?linkid=2275602 > ~/Downloads/azure-data-studio.deb
sudo apt install ~/Downloads/azure-data-studio.deb -y
mkdir -p ~/.azuredatastudio
curl -L https://raw.githubusercontent.com/jeffwilson515/penguin/main/argv.json > ~/.azuredatastudio/argv.json

# PowerShell (not working)
# source /etc/os-release
# wget -q https://packages.microsoft.com/config/debian/$VERSION_ID/packages-microsoft-prod.deb
# sudo dpkg -i packages-microsoft-prod.deb
# rm packages-microsoft-prod.deb
# sudo apt-get update
# sudo apt-get install -y powershell

# Chrome
curl -L https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb > ~/Downloads/chrome.deb
sudo apt install ~/Downloads/chrome.deb -y

# SQL Server
wget -q -O- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /usr/share/keyrings/microsoft.gpg > /dev/null 2>&1
echo "deb [signed-by=/usr/share/keyrings/microsoft.gpg arch=amd64,armhf,arm64] https://packages.microsoft.com/ubuntu/22.04/mssql-server-2022 jammy main" | sudo tee /etc/apt/sources.list.d/mssql-server-2022.list
sudo apt update
sudo apt install mssql-server -y

# MS SQL ODBC Driver 18
curl https://packages.microsoft.com/config/debian/12/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list
sudo apt-get update
sudo ACCEPT_EULA=Y apt-get install -y msodbcsql18

# Python 3 virtual environment
sudo apt install python3.11-venv -y

#Upgate everything
sudo apt-file update
sudo apt update
sudo apt upgrade -y

# SQL Config
sudo /opt/mssql/bin/mssql-conf setup
